### ISSUE TITLE
Firmware in use

### ISSUE THREAD

**Issue by themightydeity** [Tropicao/zll-gateway#1]
It would be nice to see which firmware for CC2531 is in use for the dongle to work properly? Would you be able to include that in README.

**Comment by Tropicao** [comment]
Hello,
indeed, it is planned to add proper documentation about how to generate firmware. I will do it as soon as I finish current task (separating code between proper layers)
But as a quick summary, the used firmware is generated with ZStack 3.0, with GenericApp in Home Automation directory as a base (IAR needed). I will list exact build flag and get back to this ticket when it is done

**Comment by themightydeity** [comment]
@Tropicao I resolved on using zigbee4java for now. But thanks for the information.

**Comment by Tropicao** [comment]
Indeed a switch on another project seems to be a better choice fo nom IMHO if you have specific needs, since my project is still under heavy development. Glad you have found an alternative.

**Comment by itsmepetrov** [comment]
Please provide  already generated  firmware image

**Comment by Tropicao** [comment]
Hi @itsmepetrov, I have added a sample firmware in the repository (sorry for late answer). It is not exactly the firmware based on build instructions in the repository, but if after more tests it is proven to work better than initial firmware, I will update build instructions.
